#!/usr/bin/env bash
# Mirror ~/.claude/skills into this bundle so the folder can be handed to anyone.
# Re-run after any skill edit. Review `git diff` before committing — this artifact
# is what other people install.
set -euo pipefail

SRC="${CLAUDE_SKILLS_SRC:-$HOME/.claude/skills}"
BUNDLE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEST="$BUNDLE/claude-code/skills"

[ -d "$SRC" ] || { echo "error: no skills at $SRC" >&2; exit 1; }

echo "==> Secret scan on $SRC"
if grep -rIlE '(ghp_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|xox[baprs]-[A-Za-z0-9-]{10,}|sk-[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16}|BEGIN [A-Z ]*PRIVATE KEY)' "$SRC" 2>/dev/null; then
  echo "REFUSING TO SYNC: literal credential found above. Remove it first." >&2
  exit 1
fi
echo "    clean"

echo "==> Mirroring $SRC -> $DEST"
mkdir -p "$DEST"
rsync -a --copy-links --delete \
  --exclude '.DS_Store' --exclude '__pycache__' --exclude '*.pyc' \
  --exclude 'project-config.local.md' --exclude '*.local.md' \
  --exclude 'events.jsonl*' --exclude 'DISABLED' \
  "$SRC"/ "$DEST"/

# PIPELINE.md lives at both the bundle root and inside skills/ so it is found either way.
[ -f "$DEST/PIPELINE.md" ] && cp "$DEST/PIPELINE.md" "$BUNDLE/PIPELINE.md"

"$BUNDLE/export-hermes.sh"

echo "==> De-identification check on the bundle"
# PROJECT-CONFIG.md is exempt: its whole purpose is to SHOW what these values look like.
LEAK=$(grep -RnE '[0-9]{6}:[0-9a-f]{8}-|[a-z0-9-]+\.atlassian\.net|[a-z0-9-]+\.netlify\.app/|customfield_1[0-9]{4}' \
  "$BUNDLE" --exclude-dir=.git 2>/dev/null \
  | grep -v '/PROJECT-CONFIG\.md:' \
  | grep -vE 'your-domain\.atlassian\.net|acme\.atlassian\.net|<site>\.netlify\.app|<[a-z-]+>\.atlassian\.net|acme\.example\.com|customfield_XXXXX' || true)
if [ -n "$LEAK" ]; then
  echo "REFUSING TO SYNC — identifying value leaked back into a skill:" >&2
  echo "$LEAK" | head -10 >&2
  echo "Replace it with a {{PLACEHOLDER}} and add the key to PROJECT-CONFIG.md." >&2
  exit 1
fi
# Require a real-looking username: must start with a letter or digit. That way
# documentation placeholders (/Users/..., /Users/<name>) are not flagged, while an
# actual leaked path is.
HOMELEAK=$(grep -RnIE "/Users/[A-Za-z0-9][A-Za-z0-9._-]*" "$BUNDLE" --exclude-dir=.git 2>/dev/null \
  | grep -v '\$HOME' \
  | grep -viE '/Users/(someone|user|you|example)(/|$)' || true)
if [ -n "$HOMELEAK" ]; then
  echo "REFUSING TO SYNC — a personal filesystem path leaked into a skill:" >&2
  echo "$HOMELEAK" | head -10 >&2
  echo 'Use $HOME or $REPO_ROOT instead of an absolute /Users/<name> path.' >&2
  exit 1
fi
echo "    no account ids, site hosts, deployed URLs, or personal paths in the bundle"
[ -f "$DEST/project-config.local.md" ] && { echo "REFUSING: local config leaked into bundle" >&2; exit 1; }

echo "==> Regenerating MANIFEST.md"
{
  echo "# Manifest"
  echo
  echo "Generated by \`sync-skills.sh\`. Do not edit by hand."
  echo
  echo "| Skill | Version | Description |"
  echo "|---|---|---|"
  for f in "$DEST"/*/SKILL.md; do
    d=$(basename "$(dirname "$f")")
    v=$(grep -m1 '^version:' "$f" | sed 's/version: *//' || true)
    desc=$(grep -m1 '^description:' "$f" | sed 's/description: *//;s/^"//;s/"$//' | cut -c1-160)
    printf '| `%s` | %s | %s |\n' "$d" "${v:---}" "$desc"
  done
  echo
  echo "Skills: $(find "$DEST" -name SKILL.md | wc -l | tr -d ' ')"
  echo "Reference files: $(find "$DEST" -path '*/references/*' -type f | wc -l | tr -d ' ')"
} > "$BUNDLE/MANIFEST.md"

echo "==> Done. $(find "$DEST" -name SKILL.md | wc -l | tr -d ' ') skills mirrored."
echo "    Review: git -C \"$BUNDLE\" diff"
