#!/usr/bin/env python3
"""Generate templates/TEMPLATES.md — the ADF template routing index.

Every JIRA artifact this pipeline posts must come from a template file, never
hand-composed ADF. This index is the map from "which skill, at which gate" to
"which template file". Generated by build.sh; do not edit TEMPLATES.md.

Descriptions come from _src/_routing.tsv (skill<TAB>artifact<TAB>what<TAB>when).
A template with no routing row is reported, so a new template cannot be added
without saying when it is used.
"""
import pathlib, sys

skills = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else '.')
src = skills / 'templates/adf/_src'

routing = {}
tsv = src / '_routing.tsv'
if tsv.exists():
    for line in tsv.read_text().splitlines():
        if not line.strip() or line.startswith('#'):
            continue
        parts = line.split('\t')
        if len(parts) >= 4:
            routing[(parts[0], parts[1])] = (parts[2], parts[3])

def command(skill):
    """The slash command a skill is actually invoked by, not its directory name."""
    f = skills / skill / 'SKILL.md'
    if f.exists():
        for line in f.read_text().splitlines():
            if line.startswith('description:'):
                import re
                m = re.search(r'\((/[a-z-]+)', line)
                if m:
                    return m.group(1)
                break
    return '/' + skill

rows, unrouted = [], []
for d in sorted(src.glob('*/')):
    skill = d.name
    if not (skills / skill).exists():
        continue
    for md in sorted(d.glob('*.adf.md')):
        art = md.name[:-len('.adf.md')]
        built = skills / skill / 'templates/adf' / f'{art}.adf.json'
        what, when = routing.get((skill, art), ('', ''))
        if not what and art != 'comment':
            unrouted.append(f'{skill}/{art}')
        rows.append((skill, art, what, when, built.exists(), command(skill)))

out = ['# ADF template routing index', '',
       'Generated by `templates/adf/build.sh`. Do not edit by hand.', '',
       'Templates are **strict**: every JIRA description, comment, reply, and subtask',
       'body is posted from one of these files, substituted — never hand-composed ADF',
       'and never wiki markup, HTML, or raw Markdown. Each skill owns its own templates',
       'under `<skill>/templates/adf/`; paths in a SKILL.md are relative to that skill.', '',
       'Validate before posting:', '',
       '```bash', 'python3 scripts/adf.py --validate <filled>.adf.json', '```', '',
       '## Artifact templates', '',
       '| Skill | Template | Posts | Use it when |', '|---|---|---|---|']

for skill, art, what, when, ok, cmd in rows:
    if art == 'comment':
        continue
    flag = '' if ok else ' ⚠ not built'
    out.append(f'| `{cmd}` | `{skill}/templates/adf/{art}.adf.json`{flag} | {what} | {when} |')

out += ['', '## Comment template', '',
        'Every posting skill also owns `<skill>/templates/adf/comment.adf.json` for any',
        'other comment on a ticket. There is no "quick comment" exemption — a one-line',
        'comment uses the template too.', '',
        f'Skills with a comment template: '
        + ', '.join(f'`{s}`' for s, a, *_ in rows if a == 'comment') + '.', '',
        '## Editing', '',
        'Sources are `templates/adf/_src/<skill>/<artifact>.adf.md`; the routing text in',
        'this table comes from `templates/adf/_src/_routing.tsv`. Edit the source and run',
        '`templates/adf/build.sh` — never edit the generated `.adf.json` or this file.', '',
        'Full ADF node spec: `rules/ADF.md`.', '']

(skills / 'templates/TEMPLATES.md').write_text('\n'.join(out))
print(f'  ok    routing index                 TEMPLATES.md ({len(rows)} templates)')
if unrouted:
    print('  warn  no routing row for: ' + ', '.join(unrouted))
